spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/seubanco
    username: postgres
    password: pix2000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: usuario-backend

server:
  port: 8080
